version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-26-alpha
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
   # start the emulator
     - emulator -avd circleci-android22 -no-audio -no-window:
         background: true
         parallel: true
     # wait for it to have booted
     - circle-android wait-for-boot
     # unlock the emulator screen
    - run:
        name: Wait emulator
        command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
          adb shell input keyevent 82
    - run:
        name: Run EspressoTests
        command: ./gradlew connecteddebugAndroidTest
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/reports/androidTests/connected
workflows:
  version: 2
  workflow:
    jobs:
    - build