version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-26-alpha
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Setup emulator
        command: sdkmanager "system-images;android-17;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-17;default;armeabi-v7a"
    - run:
        name: Run EspressoTests
        command: ./gradlew connecteddebugAndroidTest
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/reports/androidTests/connected
workflows:
  version: 2
  workflow:
    jobs:
    - build